export default {
  adjust: 'mdc-toolbar--fixed-adjust',
  fixed: 'mdc-toolbar--fixed',
  fixedLastRow: 'mdc-toolbar--fixed-lastrow-only',
  fixedAtLastRow: 'mdc-toolbar--fixed-at-last-row',
  flexibleDefaultBehavior: 'mdc-toolbar--flexible-default-behavior',
  flexibleMax: 'mdc-toolbar--flexible-space-maximized',
  flexibleMin: 'mdc-toolbar--flexible-space-minimized',
  icon: 'mdc-toolbar__icon',
  menuIcon: 'mdc-toolbar__menu-icon',
  root: 'mdc-toolbar',
  row: 'mdc-toolbar__row',
  section: 'mdc-toolbar__section',
  alignEnd: 'mdc-toolbar__section--align-end',
  alignStart: 'mdc-toolbar__section--align-start',
  shrinkToFit: 'mdc-toolbar__section--shrink-to-fit',
  title: 'mdc-toolbar__title',
  flexible: 'mdc-toolbar--flexible',
  waterfall: 'mdc-toolbar--waterfall',
}
